### ISSUE TITLE
Launching offer in account page is throwing error

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#33] opened 2019-05-23 11:56 UTC
The issue we are facing is once if we launch the KM article and then when i'm trying to launch Offer on account page It is saying 'These is an issue and please consult your administrator'. (Screenshot #1)

I'm observing this issue only when offer is launched after the KM article launch or any service case launch from quick links. If i directly launch the offer on account page without launching KM article or service case then offer screen is displaying correctly with content. (Screenshot #2)

1. Go to settings and configure a KM and Offer on account page.
2. launch WSS main page and login into wss.
3. Click on 'Help' on top right to launch KM article.
4. Go back to account page.
5. Click on Offer 'Learn more' option. observe the error message.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/10959887/58249531-c66d9d80-7d7c-11e9-9b06-bcfeb4e2d42b.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/10959887/58250810-db97fb80-7d7f-11e9-8133-2f4302e79f18.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 74.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ricmars** [comment] 2019-05-23 13:15
Can you attach your config file? Thanks

**Comment by Yarramneni-vasavi** [comment] 2019-05-23 16:28
Hi Richard,
Please check the attached config file.

[Healthcare-config.zip](https://github.com/pegasystems/uplus-wss/files/3213216/Healthcare-config.zip)

**Comment by ricmars** [comment] 2019-05-24 18:51
I cannot reproduce the issue - for me, both going from account directly to the offer shows an error screen - likely someone incorrect with the click through url - please check that the microsite in the pega mkt system is correctly defined.

**Comment by ricmars** [comment] 2019-05-28 17:38
Can you confirm that the issue is no longer reproducible ? Thanks

**Comment by ricmars** [comment] 2019-05-29 11:47
no update - closing the bug

**Closed by ricmars** 2019-05-29 11:47 UTC
