### ISSUE TITLE
V3 container service is erroring out after last update made on 23rd September 2022

### ISSUE THREAD

**Issue by riju1983** [pegasystems/uplus-wss#185] opened 2022-09-27 04:56 UTC
**Describe the bug**
TopOffers container (v3) is failing when invoked from U+ insurance portal.

**To Reproduce**
1. Go to setting -> Customer decision hub
2. Give host name, select channel = Web, API Level = V3, Context = Customer
3. Create Top offers Container, Create a web treatment and associate with an action.
4. Open U+ insurance portal and login using any user.
5. See error on Account page.

**Expected behavior**
An offer should appear on account page

**Screenshots**
Container request:-
{ "SubjectID":"1","ContextName":"Customer","ContainerName":"TopOffers","Direction":"Inbound","Placements":"Tile","Channel":"Web","Contexts": [{ "Key": "CurrentPage","Value":"account.html","Type": "CurrentPage"},{"Key": "PreviousPage","Value":"","Type": "PreviousPage" }]}

Response:-
{"Status":"OK","ContainerList":[{"Status":"OK","Message":"SLA fallback response”","ContainerName":"TopOffers","RankedResults":[{"Group":"Default","Issue":"Fallback","InteractionID":"-3358356044449273137","Category":"Category","CustomerCost":"0","WhyRelevant":"WhyRelevant","Benefits":"Benefits","Direction":"Direction","Name":"FallbackOffer","ShortDescription":"ShortDescription","PaidAudienceName":"PaidAudienceName","Identifier":"Identifier","Pricing":"Pricing","JourneyStage":"JourneyStage","JourneyStep":"JourneyStep","EligibilityDescription":"EligibilityDescription","Propensity":"0","AgentCompensation":"0","Priority":"0","ClassIdentifier":"Offer","Channel":"Channel","ImageURL":"ImageURL","Rank":"1","BundleParent":"BundleParent","Variant":"Variant","Treatment":"Treatment","InternalCost":"0","CampaignID":"CampaignID","OfferValue":"0","ClickThroughURL":"ClickThroughURL","Journey":"Journey"}]}]}

Tracer Error on service:-

Java Exception: 	com.pega.pegarules.data.external.clipboard.StacklessUnsupportedOperationException: Because lightweight clipboard mode is enabled, execution has failed.
Message : Property is a reference or autopopulate property and is currently not supported by redux. on property reference : DecisionRequest.Customer 
This is a stackless exception. To view the Full stack trace, please retry your scenario with debug logging enabled for logger named : "NewGenClipboardFullStacktraceLogger" 

**Desktop (please complete the following information):**
 - OS: - Windows 11
 - Browser - chrome, IE
 - Version [IE 11, Chrome 105.0.5195.102]

**Additional context**
If we test service from Pega with same request, it is working and giving us offer.

**Comment by ricmars** [comment] 2022-09-27 18:48
error is purely server side - there was no change done recently in the request sent to the CDH - It is not an issue with uplus

**Comment by riju1983** [comment] 2022-09-30 15:22
Hello, thanks for your response. For you information, the service is Pega OOTB and in locked ruleset so we can't make any changes. more ever we can see there was a change in CDH offer redirection on 23rd September. Kindly verify once more,

**Comment by ricmars** [comment] 2022-09-30 21:57
the change done on Sep 20 - https://github.com/pegasystems/uplus-wss/commit/73a2cfa280eb44931a0a67ad8726bfc1448d8d12 should only affect if the URL configured in the CDH starts by /offer which should not be the case - if you provide a config file to reproduce the issue, I can look into it but I doubt that this is related to this change. It looks like a data page configuration issue.

**Comment by riju1983** [comment] 2022-10-10 12:29
{"i18n":{"defaultlocale":"en","languages":["en"],"showLangSwitch":false},"general":{"theming":{"override":false,"interactiveColor":"#0076DE","brandColor":"#3C8712"},"ga":{"enabled":true,"trackingid":"G-RJ6VT2L72P"},"connection":{"type":"mashup","authtype":"basic","clientid":"","clientsecret":"","webportal":"","c11nserver":"","showAttachments":true},"auth_2fa":{"enabled":false,"sendMode":"email","url":"","emailSettings":{"correspondenceName":"pyDefaultOTPCorr","emailAccount":"Default","subject":"New OTP Request","validateMaxAge":"false"},"smsSettings":{"from":"Pega","account":"Default","message":"Uplus OTP login code","validateMaxAge":"false"}}},"quicklinks":[{"title":{"en":"Add Driver"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Auto-AddDriver","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-car-solid","extraparam":"PolicyID=PA1411133384","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Auto Accident"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-FNOL-Auto-Pers","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-car-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Change Address"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-ChangeAddress","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-home-alt-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Change Beneficiary"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Life-ChangeBeneficiary","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Make Payment"},"action":"createNewWork","actionparam":"","objclass":"PegaCPMI-Work-Service-MakePayment","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Policy Loan"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Life-PolicyLoan","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"PolicyID=LF1446571166","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Report a Death Claim"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-FNOL-Life","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Surrender Policy"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-Life-PolicySurrender","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-life-ring-solid","extraparam":"PolicyID=LF1446571166","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Travel Quote"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-MicroIns-Travel","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-plane-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""},{"title":{"en":"Update Billing"},"action":"createNewWork","actionparam":"","objclass":"PegaIns-Serv-Work-UpdateBillingFrequency","url":"","startcase":"pyStartCase","application":"CSISelfService","icon":"pi-home-alt-solid","extraparam":"","hide":false,"channelid":"","tenantid":"","dataretained":true,"hideusers":"","heading":""}],"billpay":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","extraparam":"","hidebillpay":false,"channelid":"","tenantid":"","dataretained":true,"heading":""},"banner":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","extraparam":"","hidebanner":true,"hidebanner_button":false,"color":"#CE9840","channelid":"","tenantid":"","dataretained":true,"heading":""},"todo":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","extraparam":"","hideactivity":false,"hideaccount":false,"hideKPI":true,"channelid":"","tenantid":"","dataretained":true,"heading":""},"kmhelp":{"action":"display","actionparam":"KMHelpSitePortal","objclass":"Data-Portal","url":"","startcase":"pyStartCase","application":"","extraparam":"","username":"","password":"","channelid":"","tenantid":"","dataretained":true,"heading":""},"activity":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","extraparam":"","channelid":"","tenantid":"","dataretained":true,"heading":""},"homeheroaction":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","pega_userid":"JimJohnson@pegatsdemo.com","pega_pwd":"rules","extraparam":"","channelid":"","tenantid":"","dataretained":true,"heading":""},"offeraction":{"action":"createNewWork","actionparam":"","objclass":"","url":"","startcase":"pyStartCase","application":"","pega_userid":"","pega_pwd":"","extraparam":"","channelid":"","tenantid":"","dataretained":true,"heading":""},"users":[{"username":"JimJohnson@pegatsdemo.com","password":"rules","img":"avatar-1.jpg","company_name":"","name":"","accountID":"","contactID":"CONT-29","customerID":"1","extraparam":"","dmm_context_data":"","pega_userid":"jim.johnson9870@gmail.com","pega_pwd":"install12345!","bill_pay":164.8,"load_by_default":true,"otp_send_to":"","billpay":164.8},{"username":"MaryJohnson07@pegatsdemo.com","password":"rules","img":"avatar-maryjohnson.jpg","company_name":"","name":"","accountID":"","contactID":"CONT-28","customerID":"2","extraparam":"","dmm_context_data":"","pega_userid":"mary.johnson1812@gmail.com","pega_pwd":"install12345!","bill_pay":164.8,"load_by_default":true,"otp_send_to":"","billpay":164.8}],"pega_chat":{"WCBConfigName":"","WebChatBotID":"","ApplicationName":"sip","MashupURL":"https://exavalu01.pegalabs.io/prweb/PRServlet/","ShowAsButton":true,"EnableProActiveNotification":false,"ResetLogout":false,"ProActiveNotificationDismissTime":"","CoBrowseServerURL":"","CoBrowseToken":"","UseLegacyWebChat":false,"DMMURL":"","DMMID":"pega-wm-chat","DMMSecret":"","DMMPrivateURL":"https://ksxyk0i2hb.execute-api.us-east-1.amazonaws.com/Prod/private-data","TenantID":""},"pega_marketing":{"Host":"https://exavalu01.pegalabs.io","Port":"","channel":"Web","requestTimeout":10000,"replaceHomePageHeader":false,"showAIOverlay":true,"enableRTS":false,"enableClickStream":true,"useCaptureByChannel":true,"apiLevel":"V3","contextName":"Customer","showLoadingIndicator":false,"appID":"","homePage":{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"TopURL"},"accountPage":{"containerName":"TopOffers","placement":"Tile","clickaction":"BuiltIn"},"phonePage":{"containerName":"","placement":"Tile","clickaction":"Mashup"},"offerPage":{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"},"extraOfferPages":[{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"},{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"},{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"},{"containerName":"TopOffers","placement":"Hero,Tile,Tile,Tile","clickaction":"Mashup"}]}}

**Comment by ricmars** [comment] 2022-10-10 16:05
this system is not accessible remotely / publicly - having said that in your description, the clickThroughURL is incorrect and seems to be coming back with the value 'clickThroughURL' which is incorrect

**Comment by ricmars** [comment] 2022-10-10 16:07
it is not clear from the description if the issue is happing when requesting the offer after login to the account using the 'Container' api endpoint or it is happening when click on learn more to open the offer - if this is the opening of the offer, this is coming from the clickthroughurl

**Comment by ricmars** [comment] 2022-10-17 17:52
no update for the past 7 days - closing issue

**Closed by ricmars** 2022-10-17 17:52 UTC
