### ISSUE TITLE
css not applied to DL header

### ISSUE THREAD

**Issue by Kalyanvenkat** [pegasystems/uplus-wss#15] opened 2019-05-20 06:06 UTC
**Describe the bug**
CSS is not applied to DL header
**To Reproduce**
1. Add header to a DL
2. Apply css(text-bold) in Header CSS class field(refer attachment).

![2019-05-20 11_35_18-Pega Dev Studio](https://user-images.githubusercontent.com/12446675/57999553-69ab8200-7af3-11e9-94a1-3a3841387b12.png)

**Comment by ricmars** [comment] 2019-05-21 11:24
this is not a bug for the uplus wss application but for the Clarity Theme

**Comment by ricmars** [comment] 2019-05-22 23:16
test-bold has been merged in the Clarity Theme - take the latest build

**Closed by ricmars** 2019-05-22 23:16 UTC
